modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="template" #mandatory
version="1.0" #mandatory
displayName="§a§lTemplate§f" #mandatory
#displayURL="" #optional
logoFile="logo.png" #optional
#credits="" #optional
authors="§a§lsxmurxy§f" #optional
description='''?'''